
import os
import sys
import time
import argparse
import json
from pathlib import Path

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

PROJECT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_DIR / "src"
PROMPT_PATH = PROJECT_DIR / "prompts" / "direct_prompt.txt"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from json_validator import validate_json_output

MODEL_ID = "google/gemma-2-2b-it"


def get_hf_token():
    token = os.environ.get("HF_TOKEN")

    if token:
        return token

    try:
        from google.colab import userdata
        token = userdata.get("HF_TOKEN")
        return token
    except Exception:
        return None


def load_model():
    hf_token = get_hf_token()

    if hf_token is None:
        raise ValueError(
            "HF_TOKEN not found. Set it as an environment variable or Colab Secret."
        )

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True
    )

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_ID,
        token=hf_token
    )

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        token=hf_token,
        quantization_config=bnb_config,
        device_map="auto",
        dtype=torch.float16
    )

    model.eval()

    return tokenizer, model


def classify_direct(text, tokenizer, model, max_new_tokens=120):
    with open(PROMPT_PATH, "r", encoding="utf-8") as f:
        prompt_template = f.read()

    safe_text = str(text).replace('"', "'")
    prompt = prompt_template.replace("{input_text}", safe_text)

    messages = [
        {
            "role": "user",
            "content": prompt
        }
    ]

    chat_text = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=False
    )

    inputs = tokenizer(
        chat_text,
        return_tensors="pt",
        truncation=True,
        max_length=2048
    ).to(model.device)

    prompt_length = inputs["input_ids"].shape[-1]

    start_time = time.time()

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    latency_ms = (time.time() - start_time) * 1000

    generated_ids = output_ids[0][prompt_length:]
    raw_output = tokenizer.decode(generated_ids, skip_special_tokens=True)

    parsed, is_valid, error = validate_json_output(raw_output)

    generated_tokens = len(generated_ids)
    tokens_per_sec = generated_tokens / (latency_ms / 1000) if latency_ms > 0 else 0

    result = {
        "label": parsed["label"],
        "category": parsed["category"],
        "confidence": parsed["confidence"],
        "short_rationale": parsed["short_rationale"],
        "json_valid": is_valid,
        "validator_error": error,
        "latency_ms": round(latency_ms, 2),
        "generated_tokens": generated_tokens,
        "tokens_per_sec": round(tokens_per_sec, 2),
        "raw_model_output": raw_output
    }

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Demo CLI for Gemma LLM-as-a-Judge toxicity moderation."
    )

    parser.add_argument(
        "--text",
        type=str,
        required=True,
        help="Input text to classify."
    )

    parser.add_argument(
        "--max_new_tokens",
        type=int,
        default=120,
        help="Maximum number of tokens generated by the model."
    )

    args = parser.parse_args()

    tokenizer, model = load_model()

    result = classify_direct(
        text=args.text,
        tokenizer=tokenizer,
        model=model,
        max_new_tokens=args.max_new_tokens
    )

    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
